app:
  test: "Hello There"
  # We will get there when we get there


# The API that is supposed to be used only by the application or "app"
app_api:

  # On what port to run the spring boot listener
  port: 25533


dev_api:
  test: "Hello There"
  # We will get there when we get there

loadbalancer:
  test: "Hello There"
  # We will get there when we get there


# Using Log4j2  |  Customizations are done at the end of developing the applications
logger:

  # for switch application should the logging be enabled
  enabled:
    app: false
    app_api: true
    dev_api: true
    loadbalancer: true

  console:

    # how it will look in the console
    log_pattern: "hours:%d{HH} minutes:%d{mm} seconds:%d{ss} Console Logs [%t] %-5level %logger{36} - %msg%n"

  # when saving the logs in files like log.xml
  file:
    # how it will look like in the log.xml file
    log_pattern: "hours:%d{HH} minutes:%d{mm} seconds:%d{ss} File Logs [%t] %-5level %logger{36} - %msg%n"

    # The name of file
    name: "log"